server:
  port: 8080
spring:
  rabbitmq:
    host: 192.168.126.128
    username: guest
    password: guest
  profiles:
    active: dev

xxl:
  job:
    accessToken: ''
    admin:
      addresses: https://orion-scheduling-k8s.cosyfriend.net/scheduling-admin/
    executor:
      address: ''
      appname: oms-job
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 4199



